routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'LoginController@logout')->name('logout');
Auth::loginUsingId(10);
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('registerSchool', 'registerSchool@index');
Route::post('registerSchool', 'registerSchool@infoSchool')->name('infoSchool');
Route::get('registerStudent', 'registerStudentController@index')->name('registerStudent');
Route::post('registerStudent', 'registerStudentController@postinfo')->name('infoStudent');
Route::get('registerStudent/verify', 'registerStudentController@verify')->name('verify');
Route::post('registerStudent/verify', 'registerStudentController@postverify')->name('postverify');
Route::get('registerStudent/resend-code', 'registerStudentController@resendCode')->name('resend-code');

// Route::middleware('auth')->group(function () {
    Route::get('/', 'Dashboard@index');
    Auth::loginUsingId(1);
    Route::get('/manager', 'DashbordController@index');

    Route::get('dashboard', 'DashbordController@index')->name('dashboard');
    Route::post('/dashboard', 'JobController@postjob')->name('job');
    Route::delete('/dashboard/{id}', 'JobController@deletejob')->name('deleteJob');

//bulletin routes
    Route::group(['as' => 'bulletin', 'prefix' => 'bulletin'], function () {
        Route::get('/', 'BulletinController@index');
        Route::get('/edit', 'BulletinController@edit')->name('.edit');
        Route::post('/store', 'BulletinController@store')->name('.add');
        Route::post('/delete-school/{id}', 'BulletinController@deleteSchool')->name('.delete-school');
        Route::post('/delete-yare-mehraban/{id}', 'BulletinController@deleteMehraban')->name('.delete-mehraban');
    });

//manager routes
    Route::group(['as' => 'manager.', 'prefix' => 'manager'], function () {
        Route::group(['as' => 'teacher.', 'prefix' => 'teacher'], function () {
            Route::get('/', 'ManagerPanelController\TeacherController@index')->name('index');
            Route::post('/create', 'ManagerPanelController\TeacherController@create')->name('create');
            Route::post('/edit', 'ManagerPanelController\TeacherController@update')->name('update');
            Route::post('/delete/{id}', 'ManagerPanelController\TeacherController@delete')->name('delete');
        });
        Route::group(['as' => 'student.', 'prefix' => 'student'], function () {
            Route::get('/', 'ManagerPanelController\StudentController@index')->name('index');
            Route::post('/create', 'ManagerPanelController\StudentController@create')->name('create');
            Route::post('/edit', 'ManagerPanelController\StudentController@update')->name('update');
            Route::post('/delete/{id}', 'ManagerPanelController\StudentController@delete')->name('delete');
            Route::get('/activate/{id}', 'ManagerPanelController\StudentController@activate')->name('activate');
        });
        Route::group(['as' => 'class.', 'prefix' => 'class'], function () {
            Route::get('/', 'ManagerPanelController\ClassController@index')->name('index');
            Route::post('/', 'ManagerPanelController\ClassController@addStudent')->name('add');
            Route::post('/create', 'ManagerPanelController\ClassController@create')->name('create');
            Route::post('/delete', 'ManagerPanelController\ClassController@delete')->name('delete');
            Route::post('/{id}', 'ManagerPanelController\ClassController@showStudent')->name('show');
        });
        Route::group(['as' => 'personal.', 'prefix' => 'personal'], function () {
            Route::get('/', 'ManagerPanelController\PersonalController@index')->name('index');
            Route::post('/', 'ManagerPanelController\PersonalController@create')->name('create');
            Route::post('/edit', 'ManagerPanelController\PersonalController@update')->name('update');
            Route::post('/delete/{id}', 'ManagerPanelController\PersonalController@delete')->name('delete');
        });
        Route::group(['as' => 'task.', 'prefix' => 'task'], function () {
            Route::get('/', 'ManagerPanelController\TaskController@index')->name('index');
            Route::get('/answers', 'ManagerPanelController\TaskController@answers')->name('index-answer');
            Route::get('/download', 'ManagerPanelController\TaskController@downloadFile')->name('download');
        });
    });
    Route::get('manager', 'DashbordController@index');


//student panel
    Route::group(['as' => 'student.', 'prefix' => 'student'], function () {
        Route::group(['as' => 'ticket.', 'prefix' => 'ticket'], function () {
            Route::get('/', 'TicketController@index')->name('index');
            Route::post('/create', 'TicketController@create')->name('create');
            Route::get('send', 'TicketController@sendTicket')->name('send');
        });
        Route::group(['as' => 'calender.', 'prefix' => 'calender'], function () {
            Route::get('/', 'CalenderController@index')->name('index');
        });
        Route::group(['as' => 'online.', 'prefix' => 'online'], function () {
            Route::get('/', 'StudentPanelController\OnlineClassController@index')->name('index');
        });
        Route::group(['as' => 'task.', 'prefix' => 'task'], function () {
            Route::get('/', 'StudentPanelController\TaskController@index')->name('index');
            Route::post('/', 'StudentPanelController\TaskController@answer')->name('answer');
        });
        Route::group(['as' => 'homework.', 'prefix' => 'homework'], function () {
            Route::get('/descriptive', 'StudentPanelController\HomeworkController@indexDescriptive')->name('index_descriptive');
            Route::post('/descriptive', 'StudentPanelController\HomeworkController@answerDescriptive')->name('answer_descriptive');
            Route::get('/test', 'StudentPanelController\HomeworkController@indexTest')->name('index_test');
            Route::post('/test', 'StudentPanelController\HomeworkController@answerTest')->name('answer_test');
        });
        Route::group(['as' => 'report_card.', 'prefix' => 'report_card'], function () {
            Route::get('/', 'StudentPanelController\ReportCardController@index')->name('index');
        });
        Route::group(['as' => 'disciplinary.', 'prefix' => 'disciplinary'], function () {
            Route::get('/', 'StudentPanelController\DisciplinaryController@index')->name('index');
        });
        Route::group(['as' => 'chart.', 'prefix' => 'chart'], function () {
            Route::get('/', 'ChartController@index')->name('index');
        });
    });
    Route::get('student', 'DashbordController@index');

//teacher panel
    Route::group(['as' => 'teacher.', 'prefix' => 'teacher'], function () {
        Route::group(['as' => 'ticket.', 'prefix' => 'ticket'], function () {
            Route::get('/', 'TicketController@index')->name('index');
            Route::post('/create', 'TicketController@create')->name('create');
            Route::get('/send', 'TicketController@sendTicket')->name('send');
        });
        Route::group(['as' => 'calender.', 'prefix' => 'calender'], function () {
            Route::get('/', 'CalenderController@index')->name('index');
        });
        Route::group(['as' => 'online.', 'prefix' => 'online'], function () {
            Route::get('/', 'TeacherPanelController\OnlineClassController@index')->name('index');
            Route::post('/', 'TeacherPanelController\OnlineClassController@create')->name('create');
        });
        Route::group(['as' => 'task.', 'prefix' => 'task'], function () {
            Route::get('/', 'TeacherPanelController\TaskController@index')->name('index');
            Route::post('/create', 'TeacherPanelController\TaskController@create')->name('create');
            Route::post('/update', 'TeacherPanelController\TaskController@update')->name('update');
            Route::post('/delete', 'TeacherPanelController\TaskController@delete')->name('delete');
            Route::get('/correct', 'TeacherPanelController\TaskController@correctTaskIndex')->name('correct-index');
            Route::post('/correct', 'TeacherPanelController\TaskController@correctTask')->name('correct');
            Route::get('/correct/download', 'TeacherPanelController\TaskController@downloadFile')->name('download');
        });
        Route::group(['as' => 'homework.', 'prefix' => 'homework'], function () {
            Route::get('/', 'TeacherPanelController\HomeworkController@index')->name('index');
            Route::post('/create', 'TeacherPanelController\HomeworkController@create')->name('create');
            Route::post('/update', 'TeacherPanelController\HomeworkController@update')->name('update');
            Route::post('/delete', 'TeacherPanelController\HomeworkController@delete')->name('delete');
        });
        Route::group(['as' => 'question.', 'prefix' => 'question'], function () {
            Route::post('/', 'TeacherPanelController\QuestionController@add')->name('add');
        });
        Route::group(['as' => 'report_card.', 'prefix' => 'report_card'], function () {
            Route::get('/', 'TeacherPanelController\ReportCardController@index')->name('index');
        });
        Route::group(['as' => 'disciplinary.', 'prefix' => 'disciplinary'], function () {
            Route::get('/', 'TeacherPanelController\DisciplinaryController@index')->name('index');

resources/views/panel_student/all.blade.php
@extends('panel.master')
@section('content')
    <h2>this is panel student</h2>
@endsection

resources/views/panel_student/bulletin.blade.php
@extends('panel.master')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">تابلو اعلانات</h1>
                </div><!-- /.col -->
                <!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info" style="min-height: 250px;">
                        <div class="inner">
                            <h4 style="padding-bottom:38px">حدیث هفته</h4>
                            <hr>
                            <p>{{$bulletin['hadis']?? ''}}</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-heart-o"></i>
                        </div>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success" style="min-height: 250px;">
                        <div class="inner">
                            <h4 style="padding-bottom:38px">سخن حکمت آمیز</h4>
                            <hr>
                            <p>{{$bulletin['sokhan']?? ''}}</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-balance-scale"></i>
                        </div>

                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning" style="min-height: 250px;">
                        <div class="inner">
                            <h4 style="padding-bottom:38px">شعار هفته</h4>
                            <hr>
                            <p>{{$bulletin['shoar']?? ''}}</p>

                        </div>
                        <div class="icon">
                            <i class="fa fa-volume-off"></i>
                        </div>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-danger" style="min-height: 250px;">
                        <div class="inner">
                            <h4 style="padding-bottom:38px">توصیه ها</h4>
                            <hr>
                            <p>{{$bulletin['tosiye'] ?? ''}}</p>
                        </div>
                        <div class="icon">
                            <i class="fa fa-graduation-cap"></i>
                        </div>
                    </div>
                </div>
                <!-- ./col -->
            </div>
        </div>

    </section>
    <section class="col-lg-512 connectedSortable ui-sortable">
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <div class="card bg-primary-gradient collapsed-card">
                        <div class="card-header no-border ui-sortable-handle" style="cursor: move;">
                            <h3 class="card-title">
                                <i class="fa fa-commenting-o mr-1"></i>
                                تابلو اعلانات مدرسه الکترونیکی یار مهربان
                            </h3>
                            <!-- card tools -->
                            <div class="card-tools">
                                <button type="button" class="btn btn-primary btn-sm" data-widget="collapse"
                                        data-toggle="tooltip" title="" data-original-title="Collapse">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </div>
                            <!-- /.card-tools -->
                        </div>
                        <div class="card-body ">
                            <ul class="mr-4">
                                @foreach($yare_mehraban_bulletins as $yare_mehraban_bulletin)
                                    <li>{{$yare_mehraban_bulletin->content}}</li>
                                    <form method="post"
                                          action="{{route("bulletin.delete-mehraban", $yare_mehraban_bulletin->id)}}">
                                        @csrf
                                        <button class="btn btn-danger d-flex fa-recycle">
                                            حذف
                                        </button>
                                    </form>
                                @endforeach
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-sm">
                    <div class="card bg-info-gradient collapsed-card">
                        <div class="card-header no-border ui-sortable-handle" style="cursor: move;">
                            <h3 class="card-title">
                                <i class="fa fa-comment-o mr-1"></i>
                                تابلو اعلانات مدرسه {{$school->name}}
                            </h3>

                            <div class="card-tools">
                                
                                    <a href="{{route('bulletin.edit')}}" type="button" class="btn bg-info btn-sm">
                                        <i class="fa fa-plus"></i>
                                    </a>
                            
                                <button type="button" class="btn bg-info btn-sm" data-widget="collapse">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <ul class="mr-4">
                                @foreach($school_bulletins as $school_bulletin)
                                    <li>{{$school_bulletin->content}}</li>
                                    <form method="post"
                                          action="{{route("bulletin.delete-school", $school_bulletin->id)}}">
                                        @csrf
                                        <button class="btn btn-danger d-flex fa-recycle">
                                            حذف
                                        </button>
                                    </form>
                                @endforeach
                            </ul>
                        </div>

                        <!-- /.card-footer -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Map card -->

        <!-- /.card -->

        <!-- solid sales graph -->

        <!-- /.card -->
    </section>
@endsection

resources/views/panel_student/online_class.blade.php
@extends('panel.master')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">کلاس آنلاین</h1>
                </div><!-- /.col -->
                <!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="card">
                <!-- <div class="card-header">
                      </div> -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <table class="table table-hover">
                                <tbody>
                                <tr>
                                    <th>ردیف</th>
                                    <th>نام دبیر برگزار کننده</th>
                                    <th>تاریخ و زمان شروع</th>
                                    <th>لینک</th>
                                </tr>
                                @foreach($classes as $class)
                                    <tr>
                                        <th>{{$class->id}}</th>
                                        <th>{{$class->class->teacher->user->name}} {{$class->class->teacher->user->family}}</th>
                                        <th>{{$class->created_at}}</th>
                                        <th>
                                                <a target="_blank" href="{{$class->url}}">لینک کلاس</a>
                                        </th>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->

        </div>
    </div>
    </div>
@endsection

resources/views/panel_student/task.blade.php
@extends('panel.master')
@section('content')
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">تکلیف دانش آموز</h1>
                </div><!-- /.col -->
                <!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">

            <div class="card">
                <!-- <div class="card-header">
                      </div> -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">لیست تکالیف</h3>

                                    <div class="card-tools">
                                        <div class="input-group input-group-sm" style="width: 150px;">
                                            <input type="text" name="table_search" class="form-control float-right"
                                                   placeholder="جستجو">

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-default"><i
                                                        class="fa fa-search"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body table-responsive p-0">
                                    <table class="table table-hover">
                                        <tbody>
                                        <tr>
                                            <th>ردیف</th>
                                            <th>نام درس</th>
                                            <th>عنوان تکلیف</th>
                                            <th>معلم</th>
                                            <th>تاریخ تخصیص</th>
                                            <th>نظر معلم</th>
                                            <th>نمره</th>
                                            <th>پاسخ</th>
                                        </tr>
                                        @foreach($tasks as $task)
                                            <tr>
                                                <td>{{$task->id}}</td>
                                                <td>{{$task->lesson_name}}</td>
                                                <td>{{$task->title}}</td>
                                                <td>{{$task->teacher->user->name}} {{$task->teacher->user->family}}</td>
                                                <td>{{$task->deadline}}</td>
                                                <td>
                                                    @if(isset($task->task_answer[0]->comment_teacher))
                                                        {{
                                                            $task->task_answer[0]->comment_teacher
                                                        }}
                                                    @else {{''}}
                                                    @endif
                                                </td>
                                                <td>
                                                    @if(isset($task->task_answer[0]->grade))
                                                        {{
                                                            $task->task_answer[0]->grade
                                                        }}
                                                    @else {{''}}
                                                    @endif
                                                <td>
                                                    <button id="answer-modal" type="button" class="btn btn-primary"
                                                            data-toggle="modal"
                                                            title="مشاهده و پاسخ" data-target="#modal-default"
                                                            data-id="{{$task->id}}"
                                                            data-content="{{$task->content}}"
                                                            data-answer="{{$task->task_answer[0]->answer??''}}"
                                                            data-task-answer-id="{{$task->task_answer[0]->id ?? ''}}"
                                                    ><i
                                                            class="fa fa-eye"></i></button>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->

                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->

        </div><!-- /.container-fluid -->
        <div class="modal fade" id="modal-default" style="display: none;z-index:3001;" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">پاسخ تکلیف</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form role="form" method="post" action="{{route('student.task.answer')}}"
                              enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label>تکلیف</label>
                                    <input id="data-content" type="text" class="form-control"
                                           placeholder="وارد کردن اطلاعات ..."
                                           value="در مورد کوه الوند توضیح دهید" disabled="">
                                    <input id="data-id" type="hidden" name="id">
                                    <input id="data-task-answer-id" type="hidden" name="task_answer_id">
                                </div>
                                <div class="form-group">
                                    <label>پاسخ</label>
                                    <textarea id="data-answer" class="form-control" rows="3"
                                              placeholder="پاسخ را وارد کنید ..." name="answer"></textarea>
                                </div>
                                <div class="form-group row">
                                    <div class="form-group">
                                        <label for="answer_file">ارسال فایل</label>
                                        <div class="input-group">
                                            <div class="custom-file">
                                                {{--                                                <label class="custom-file-label" for="exampleInputFile">انتخاب--}}
                                                {{--                                                    فایل</label>--}}
                                                <input type="file" id="data-file" name="answer_file">
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            </div>
                            <!-- /.card-body -->

                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">لغو</button>
                        <button type="submit" class="btn btn-primary">ثبت</button>
                        </form>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
    </div>
    <!-- /.content -->
    <script>
        $(document).ready(function () {
            $('body').on('click', '#answer-modal', function () {
                document.getElementById('data-content').value = $(this).attr('data-content');
                document.getElementById('data-answer').innerHTML = $(this).attr('data-answer');
                document.getElementById('data-id').value = $(this).attr('data-id');
                document.getElementById('data-task-answer-id').value = $(this).attr('data-task-answer-id');
            });
        });
    </script>
@endsection