routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'LoginController@logout')->name('logout');
Auth::loginUsingId(10);
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('registerSchool', 'registerSchool@index');
Route::post('registerSchool', 'registerSchool@infoSchool')->name('infoSchool');
Route::get('registerStudent', 'registerStudentController@index')->name('registerStudent');
Route::post('registerStudent', 'registerStudentController@postinfo')->name('infoStudent');
Route::get('registerStudent/verify', 'registerStudentController@verify')->name('verify');
Route::post('registerStudent/verify', 'registerStudentController@postverify')->name('postverify');
Route::get('registerStudent/resend-code', 'registerStudentController@resendCode')->name('resend-code');

// Route::middleware('auth')->group(function () {
    Route::get('/', 'Dashboard@index');
    Auth::loginUsingId(1);
    Route::get('/manager', 'DashbordController@index');

    Route::get('dashboard', 'DashbordController@index')->name('dashboard');
    Route::post('/dashboard', 'JobController@postjob')->name('job');
    Route::delete('/dashboard/{id}', 'JobController@deletejob')->name('deleteJob');

//bulletin routes
    Route::group(['as' => 'bulletin', 'prefix' => 'bulletin'], function () {
        Route::get('/', 'BulletinController@index');
        Route::get('/edit', 'BulletinController@edit')->name('.edit');
        Route::post('/store', 'BulletinController@store')->name('.add');
        Route::post('/delete-school/{id}', 'BulletinController@deleteSchool')->name('.delete-school');
        Route::post('/delete-yare-mehraban/{id}', 'BulletinController@deleteMehraban')->name('.delete-mehraban');
    });

//manager routes
    Route::group(['as' => 'manager.', 'prefix' => 'manager'], function () {
        Route::group(['as' => 'teacher.', 'prefix' => 'teacher'], function () {
            Route::get('/', 'ManagerPanelController\TeacherController@index')->name('index');
            Route::post('/create', 'ManagerPanelController\TeacherController@create')->name('create');
            Route::post('/edit', 'ManagerPanelController\TeacherController@update')->name('update');
            Route::post('/delete/{id}', 'ManagerPanelController\TeacherController@delete')->name('delete');
        });
        Route::group(['as' => 'student.', 'prefix' => 'student'], function () {
            Route::get('/', 'ManagerPanelController\StudentController@index')->name('index');
            Route::post('/create', 'ManagerPanelController\StudentController@create')->name('create');
            Route::post('/edit', 'ManagerPanelController\StudentController@update')->name('update');
            Route::post('/delete/{id}', 'ManagerPanelController\StudentController@delete')->name('delete');
            Route::get('/activate/{id}', 'ManagerPanelController\StudentController@activate')->name('activate');
        });
        Route::group(['as' => 'class.', 'prefix' => 'class'], function () {
            Route::get('/', 'ManagerPanelController\ClassController@index')->name('index');
            Route::post('/', 'ManagerPanelController\ClassController@addStudent')->name('add');
            Route::post('/create', 'ManagerPanelController\ClassController@create')->name('create');
            Route::post('/delete', 'ManagerPanelController\ClassController@delete')->name('delete');
            Route::post('/{id}', 'ManagerPanelController\ClassController@showStudent')->name('show');
        });
        Route::group(['as' => 'personal.', 'prefix' => 'personal'], function () {
            Route::get('/', 'ManagerPanelController\PersonalController@index')->name('index');
            Route::post('/', 'ManagerPanelController\PersonalController@create')->name('create');
            Route::post('/edit', 'ManagerPanelController\PersonalController@update')->name('update');
            Route::post('/delete/{id}', 'ManagerPanelController\PersonalController@delete')->name('delete');
        });
        Route::group(['as' => 'task.', 'prefix' => 'task'], function () {
            Route::get('/', 'ManagerPanelController\TaskController@index')->name('index');
            Route::get('/answers', 'ManagerPanelController\TaskController@answers')->name('index-answer');
            Route::get('/download', 'ManagerPanelController\TaskController@downloadFile')->name('download');
        });
    });
    Route::get('manager', 'DashbordController@index');


//student panel
    Route::group(['as' => 'student.', 'prefix' => 'student'], function () {
        Route::group(['as' => 'ticket.', 'prefix' => 'ticket'], function () {
            Route::get('/', 'TicketController@index')->name('index');
            Route::post('/create', 'TicketController@create')->name('create');
            Route::get('send', 'TicketController@sendTicket')->name('send');
        });
        Route::group(['as' => 'calender.', 'prefix' => 'calender'], function () {
            Route::get('/', 'CalenderController@index')->name('index');
        });
        Route::group(['as' => 'online.', 'prefix' => 'online'], function () {
            Route::get('/', 'StudentPanelController\OnlineClassController@index')->name('index');
        });
        Route::group(['as' => 'task.', 'prefix' => 'task'], function () {
            Route::get('/', 'StudentPanelController\TaskController@index')->name('index');
            Route::post('/', 'StudentPanelController\TaskController@answer')->name('answer');
        });
        Route::group(['as' => 'homework.', 'prefix' => 'homework'], function () {
            Route::get('/descriptive', 'StudentPanelController\HomeworkController@indexDescriptive')->name('index_descriptive');
            Route::post('/descriptive', 'StudentPanelController\HomeworkController@answerDescriptive')->name('answer_descriptive');
            Route::get('/test', 'StudentPanelController\HomeworkController@indexTest')->name('index_test');
            Route::post('/test', 'StudentPanelController\HomeworkController@answerTest')->name('answer_test');
        });
        Route::group(['as' => 'report_card.', 'prefix' => 'report_card'], function () {
            Route::get('/', 'StudentPanelController\ReportCardController@index')->name('index');
        });
        Route::group(['as' => 'disciplinary.', 'prefix' => 'disciplinary'], function () {
            Route::get('/', 'StudentPanelController\DisciplinaryController@index')->name('index');
        });
        Route::group(['as' => 'chart.', 'prefix' => 'chart'], function () {
            Route::get('/', 'ChartController@index')->name('index');
        });
    });
    Route::get('student', 'DashbordController@index');

//teacher panel
    Route::group(['as' => 'teacher.', 'prefix' => 'teacher'], function () {
        Route::group(['as' => 'ticket.', 'prefix' => 'ticket'], function () {
            Route::get('/', 'TicketController@index')->name('index');
            Route::post('/create', 'TicketController@create')->name('create');
            Route::get('/send', 'TicketController@sendTicket')->name('send');
        });
        Route::group(['as' => 'calender.', 'prefix' => 'calender'], function () {
            Route::get('/', 'CalenderController@index')->name('index');
        });
        Route::group(['as' => 'online.', 'prefix' => 'online'], function () {
            Route::get('/', 'TeacherPanelController\OnlineClassController@index')->name('index');
            Route::post('/', 'TeacherPanelController\OnlineClassController@create')->name('create');
        });
        Route::group(['as' => 'task.', 'prefix' => 'task'], function () {
            Route::get('/', 'TeacherPanelController\TaskController@index')->name('index');
            Route::post('/create', 'TeacherPanelController\TaskController@create')->name('create');
            Route::post('/update', 'TeacherPanelController\TaskController@update')->name('update');
            Route::post('/delete', 'TeacherPanelController\TaskController@delete')->name('delete');
            Route::get('/correct', 'TeacherPanelController\TaskController@correctTaskIndex')->name('correct-index');
            Route::post('/correct', 'TeacherPanelController\TaskController@correctTask')->name('correct');
            Route::get('/correct/download', 'TeacherPanelController\TaskController@downloadFile')->name('download');
        });
        Route::group(['as' => 'homework.', 'prefix' => 'homework'], function () {
            Route::get('/', 'TeacherPanelController\HomeworkController@index')->name('index');
            Route::post('/create', 'TeacherPanelController\HomeworkController@create')->name('create');
            Route::post('/update', 'TeacherPanelController\HomeworkController@update')->name('update');
            Route::post('/delete', 'TeacherPanelController\HomeworkController@delete')->name('delete');
        });
        Route::group(['as' => 'question.', 'prefix' => 'question'], function () {
            Route::post('/', 'TeacherPanelController\QuestionController@add')->name('add');
        });
        Route::group(['as' => 'report_card.', 'prefix' => 'report_card'], function () {
            Route::get('/', 'TeacherPanelController\ReportCardController@index')->name('index');
        });
        Route::group(['as' => 'disciplinary.', 'prefix' => 'disciplinary'], function () {
            Route::get('/', 'TeacherPanelController\DisciplinaryController@index')->name('index');

resources/views/panel_teacher/chart.blade.php
@extends('panel.master')
@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">گزارش و نمودار دانش آموز</h1>
                </div><!-- /.col -->
                <!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <!-- AREA CHART -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">ارزیابی عملکرد مطالعاتی</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                                <button type="button" class="btn btn-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="chart">
                                <canvas id="areaChart" style="height: 286px; width: 572px;" width="715" height="357"></canvas>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                    <!-- DONUT CHART -->
                    <div class="card card-danger">
                        <div class="card-header">
                            <h3 class="card-title">نسبت معالعه به نمره</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                                <button type="button" class="btn btn-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div>
                        <div class="card-body">
                            <canvas id="pieChart" style="height: 306px; width: 612px;" width="765" height="382"></canvas>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col (LEFT) -->
                <div class="col-md-6">
                    <!-- LINE CHART -->
                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">پیشرفت تحصیلی</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                                <button type="button" class="btn btn-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="chart">
                                <canvas id="lineChart" style="height: 286px; width: 572px;" width="715" height="357"></canvas>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                    <!-- BAR CHART -->
                    <div class="card card-success">
                        <div class="card-header">
                            <h3 class="card-title">نمودار مقایسه کلاسی</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                                <button type="button" class="btn btn-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="chart">
                                <canvas id="barChart" style="height: 286px; width: 572px;" width="715" height="357"></canvas>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>


                    <!-- /.card -->

                </div>
                <!-- /.col (RIGHT) -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

@endsection

resources/views/panel_teacher/online_class.blade.php
@extends('panel.master')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">کلاس آنلاین</h1>
                </div><!-- /.col -->
                <!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">

            <div class="card">
                <!-- <div class="card-header">
                      </div> -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <div class="mx-auto" style="width: 200px;margin:20px;">
                                <button type="button" class="btn btn-default">
                                    <i class="fa fa-plus"></i>
                                    <a target="_blank" href="https://meet.google.com/">کلاس جدید</a>
                                </button>
                            </div>
                            <form action="{{route('teacher.online.create')}}" method="post">
                                @csrf
                                <label>کلاس:</label>
                                <select name="class_id" class="form-control select2 form-control-sm"
                                        style="width: 40%;">
                                    @foreach($classes as $class)
                                        {{$classes}}
                                        <option value="{{$class->id}}">{{$class->label}}</option>
                                    @endforeach
                                </select>
                                <br>
                                <div>
                                        به اشتراک گذاری لینک
                                        <input type='text' name='link' id="link">
                                        <button type="submit" class='btn btn-success'>ثبت</button>
                                </div>
                            </form>
                            <!-- /.card -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->

        </div>
    </div>
    <!-- /.content -->
@endsection

resources/views/panel_teacher/task_answers.blade.php
@extends('panel.master')
@section('content')

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">لیست پاسخ تکالیف کلاس {{$class->label}}</h1>
                </div><!-- /.col -->
                <!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">

            <div class="card">
                <!-- <div class="card-header">
                      </div> -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">لیست پاسخ‌ها</h3>

                                    <div class="card-tools">
                                        <div class="input-group input-group-sm" style="width: 150px;">
                                            <input type="text" name="table_search" class="form-control float-right"
                                                   placeholder="جستجو">

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-default"><i
                                                        class="fa fa-search"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body table-responsive p-0">
                                    <table class="table table-hover">
                                        <tbody>
                                        <tr>
                                            <th>ردیف</th>
                                            <th>نام و نام خانوادگی</th>
                                            <th>نمره</th>
                                            <th>عملیات تصحیح</th>
                                        </tr>
                                        @foreach($answers as $answer)
                                            <tr>
                                                <td>{{$answer->id}}</td>
                                                <td>{{$answer->student->user->name}} {{$answer->student->user->family}}</td>
                                                <td>{{$answer->grade}} از ۲۰</td>

                                                <td>
                                                    <button id="modal" type="button" class="btn btn-primary"
                                                            data-toggle="modal"
                                                            data-target="#modal-descriptive-check-feedback"
                                                            title="ویرایش"
                                                            data-name="{{ $answer->student->user->name }}"
                                                            data-family="{{ $answer->student->user->family }}"
                                                            data-content="{{ $task->content }}"
                                                            data-answer="{{ $answer->answer }}"
                                                            data-grade="{{ $answer->grade }}"
                                                            data-comment="{{ $answer->comment_teacher }}"
                                                            data-id="{{ $answer->id }}"
                                                            data-file="{{ $answer->file_name }}"
                                                    >
                                                        <i class="fa fa-edit"></i></button>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->

                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->

            <!-- .modal-default -->
        </div><!-- /.container-fluid -->


        <div class="modal fade" id="modal-descriptive-check-feedback" style="display: none;z-index:3001;"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="student-name"></h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form role="form" method="post" action="{{route('teacher.task.correct')}}">
                            @csrf
                            <div class="card-body">
                                <div class="card collapsed-card">
                                    <div class="card-header ui-sortable-handle" style="cursor: move;">


                                        <div class="card-tools" style="left:auto;right:1rem;">
                                            <button type="button" class="btn btn-tool" data-widget="collapse">
                                                <i class="fa fa-minus"></i>
                                            </button>
                                            <span data-toggle="tooltip" title="" class="badge badge-warning"
                                                  data-original-title="3 New Messages">3 نمره</span>
                                        </div>
                                        <h3 class="card-title" style="float:left;">سوال 1</h3>
                                    </div>
                                    <!-- /.card-header -->
                                    <div class="card-body">
                                        <div class="form-group">
                                            <textarea class="form-control" rows="3"
                                                      id="question-content"
                                                      disabled></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>پاسخ دانش آموز</label>
                                            <textarea id="answer-content" class="form-control" rows="3"
                                                      placeholder="وارد کردن اطلاعات ..."
                                                      disabled></textarea>
                                        </div>
                                        <div class="form-group row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label for="exampleInputEmail1">نمره</label>
                                                    <input name="grade" type="number" step="0.01" class="form-control"
                                                           id="grade-content"
                                                           placeholder="نمره">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label for="exampleInputEmail1">نظر معلم</label>
                                                    <input name="comment" type="text" class="form-control" id="comment-content"
                                                           placeholder="نظر معلم">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <a id="download-link" class="btn btn-large pull-right"><i
                                                    class="icon-download-alt"> </i> دانلود پاسخ </a>
                                            <div class="form-group">
                                                <input name="id" type="hidden" class="form-control" id="edit-id">
                                            </div>
                                        </div>
                                        <!-- /.direct-chat-pane -->
                                    </div>
                                    <!-- /.card-body -->
                                    <!-- /.card-footer-->
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="modal-footer justify-content-between">
                                <button type="button" class="btn btn-default" data-dismiss="modal">لغو</button>
                                <button type="submit" class="btn btn-primary">ثبت نهایی</button>
                            </div>
                         </form>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>


    </div>
    <!-- /.content -->
    <script>
        $(document).ready(function () {
            $('body').on('click', '#modal', function () {
                document.getElementById('student-name').innerHTML = 'پاسخ تکلیف دانش آموز ' + $(this).attr('data-name') + ' ' + $(this).attr('data-family');
                document.getElementById('question-content').innerHTML = $(this).attr('data-content');
                document.getElementById('answer-content').innerHTML = $(this).attr('data-answer');
                document.getElementById('grade-content').value = $(this).attr('data-grade');
                document.getElementById('comment-content').value = $(this).attr('data-comment');
                document.getElementById('edit-id').value = $(this).attr('data-id');
                var file = $(this).attr('data-file')
                if (file) {
                    document.getElementById('download-link').href = 'correct/download?id=' + $(this).attr('data-id')
                }
            });
        });
    </script>
@endsection