routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'LoginController@logout')->name('logout');
Auth::loginUsingId(10);
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('registerSchool', 'registerSchool@index');
Route::post('registerSchool', 'registerSchool@infoSchool')->name('infoSchool');
Route::get('registerStudent', 'registerStudentController@index')->name('registerStudent');
Route::post('registerStudent', 'registerStudentController@postinfo')->name('infoStudent');
Route::get('registerStudent/verify', 'registerStudentController@verify')->name('verify');
Route::post('registerStudent/verify', 'registerStudentController@postverify')->name('postverify');
Route::get('registerStudent/resend-code', 'registerStudentController@resendCode')->name('resend-code');

// Route::middleware('auth')->group(function () {
    Route::get('/', 'Dashboard@index');
    Auth::loginUsingId(1);
    Route::get('/manager', 'DashbordController@index');

    Route::get('dashboard', 'DashbordController@index')->name('dashboard');
    Route::post('/dashboard', 'JobController@postjob')->name('job');
    Route::delete('/dashboard/{id}', 'JobController@deletejob')->name('deleteJob');

//bulletin routes
    Route::group(['as' => 'bulletin', 'prefix' => 'bulletin'], function () {
        Route::get('/', 'BulletinController@index');
        Route::get('/edit', 'BulletinController@edit')->name('.edit');
        Route::post('/store', 'BulletinController@store')->name('.add');
        Route::post('/delete-school/{id}', 'BulletinController@deleteSchool')->name('.delete-school');
        Route::post('/delete-yare-mehraban/{id}', 'BulletinController@deleteMehraban')->name('.delete-mehraban');
    });

//manager routes
    Route::group(['as' => 'manager.', 'prefix' => 'manager'], function () {
        Route::group(['as' => 'teacher.', 'prefix' => 'teacher'], function () {
            Route::get('/', 'ManagerPanelController\TeacherController@index')->name('index');
            Route::post('/create', 'ManagerPanelController\TeacherController@create')->name('create');
            Route::post('/edit', 'ManagerPanelController\TeacherController@update')->name('update');
            Route::post('/delete/{id}', 'ManagerPanelController\TeacherController@delete')->name('delete');
        });
        Route::group(['as' => 'student.', 'prefix' => 'student'], function () {
            Route::get('/', 'ManagerPanelController\StudentController@index')->name('index');
            Route::post('/create', 'ManagerPanelController\StudentController@create')->name('create');
            Route::post('/edit', 'ManagerPanelController\StudentController@update')->name('update');
            Route::post('/delete/{id}', 'ManagerPanelController\StudentController@delete')->name('delete');
            Route::get('/activate/{id}', 'ManagerPanelController\StudentController@activate')->name('activate');
        });
        Route::group(['as' => 'class.', 'prefix' => 'class'], function () {
            Route::get('/', 'ManagerPanelController\ClassController@index')->name('index');
            Route::post('/', 'ManagerPanelController\ClassController@addStudent')->name('add');
            Route::post('/create', 'ManagerPanelController\ClassController@create')->name('create');
            Route::post('/delete', 'ManagerPanelController\ClassController@delete')->name('delete');
            Route::post('/{id}', 'ManagerPanelController\ClassController@showStudent')->name('show');
        });
        Route::group(['as' => 'personal.', 'prefix' => 'personal'], function () {
            Route::get('/', 'ManagerPanelController\PersonalController@index')->name('index');
            Route::post('/', 'ManagerPanelController\PersonalController@create')->name('create');
            Route::post('/edit', 'ManagerPanelController\PersonalController@update')->name('update');
            Route::post('/delete/{id}', 'ManagerPanelController\PersonalController@delete')->name('delete');
        });
        Route::group(['as' => 'task.', 'prefix' => 'task'], function () {
            Route::get('/', 'ManagerPanelController\TaskController@index')->name('index');
            Route::get('/answers', 'ManagerPanelController\TaskController@answers')->name('index-answer');
            Route::get('/download', 'ManagerPanelController\TaskController@downloadFile')->name('download');
        });
    });
    Route::get('manager', 'DashbordController@index');


//student panel
    Route::group(['as' => 'student.', 'prefix' => 'student'], function () {
        Route::group(['as' => 'ticket.', 'prefix' => 'ticket'], function () {
            Route::get('/', 'TicketController@index')->name('index');
            Route::post('/create', 'TicketController@create')->name('create');
            Route::get('send', 'TicketController@sendTicket')->name('send');
        });
        Route::group(['as' => 'calender.', 'prefix' => 'calender'], function () {
            Route::get('/', 'CalenderController@index')->name('index');
        });
        Route::group(['as' => 'online.', 'prefix' => 'online'], function () {
            Route::get('/', 'StudentPanelController\OnlineClassController@index')->name('index');
        });
        Route::group(['as' => 'task.', 'prefix' => 'task'], function () {
            Route::get('/', 'StudentPanelController\TaskController@index')->name('index');
            Route::post('/', 'StudentPanelController\TaskController@answer')->name('answer');
        });
        Route::group(['as' => 'homework.', 'prefix' => 'homework'], function () {
            Route::get('/descriptive', 'StudentPanelController\HomeworkController@indexDescriptive')->name('index_descriptive');
            Route::post('/descriptive', 'StudentPanelController\HomeworkController@answerDescriptive')->name('answer_descriptive');
            Route::get('/test', 'StudentPanelController\HomeworkController@indexTest')->name('index_test');
            Route::post('/test', 'StudentPanelController\HomeworkController@answerTest')->name('answer_test');
        });
        Route::group(['as' => 'report_card.', 'prefix' => 'report_card'], function () {
            Route::get('/', 'StudentPanelController\ReportCardController@index')->name('index');
        });
        Route::group(['as' => 'disciplinary.', 'prefix' => 'disciplinary'], function () {
            Route::get('/', 'StudentPanelController\DisciplinaryController@index')->name('index');
        });
        Route::group(['as' => 'chart.', 'prefix' => 'chart'], function () {
            Route::get('/', 'ChartController@index')->name('index');
        });
    });
    Route::get('student', 'DashbordController@index');

//teacher panel
    Route::group(['as' => 'teacher.', 'prefix' => 'teacher'], function () {
        Route::group(['as' => 'ticket.', 'prefix' => 'ticket'], function () {
            Route::get('/', 'TicketController@index')->name('index');
            Route::post('/create', 'TicketController@create')->name('create');
            Route::get('/send', 'TicketController@sendTicket')->name('send');
        });
        Route::group(['as' => 'calender.', 'prefix' => 'calender'], function () {
            Route::get('/', 'CalenderController@index')->name('index');
        });
        Route::group(['as' => 'online.', 'prefix' => 'online'], function () {
            Route::get('/', 'TeacherPanelController\OnlineClassController@index')->name('index');
            Route::post('/', 'TeacherPanelController\OnlineClassController@create')->name('create');
        });
        Route::group(['as' => 'task.', 'prefix' => 'task'], function () {
            Route::get('/', 'TeacherPanelController\TaskController@index')->name('index');
            Route::post('/create', 'TeacherPanelController\TaskController@create')->name('create');
            Route::post('/update', 'TeacherPanelController\TaskController@update')->name('update');
            Route::post('/delete', 'TeacherPanelController\TaskController@delete')->name('delete');
            Route::get('/correct', 'TeacherPanelController\TaskController@correctTaskIndex')->name('correct-index');
            Route::post('/correct', 'TeacherPanelController\TaskController@correctTask')->name('correct');
            Route::get('/correct/download', 'TeacherPanelController\TaskController@downloadFile')->name('download');
        });
        Route::group(['as' => 'homework.', 'prefix' => 'homework'], function () {
            Route::get('/', 'TeacherPanelController\HomeworkController@index')->name('index');
            Route::post('/create', 'TeacherPanelController\HomeworkController@create')->name('create');
            Route::post('/update', 'TeacherPanelController\HomeworkController@update')->name('update');
            Route::post('/delete', 'TeacherPanelController\HomeworkController@delete')->name('delete');
        });
        Route::group(['as' => 'question.', 'prefix' => 'question'], function () {
            Route::post('/', 'TeacherPanelController\QuestionController@add')->name('add');
        });
        Route::group(['as' => 'report_card.', 'prefix' => 'report_card'], function () {
            Route::get('/', 'TeacherPanelController\ReportCardController@index')->name('index');
        });
        Route::group(['as' => 'disciplinary.', 'prefix' => 'disciplinary'], function () {
            Route::get('/', 'TeacherPanelController\DisciplinaryController@index')->name('index');

resources/views/panel/master.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>پنل مدیریت | داشبورد اول</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    @include('panel.frontend.css')

</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <!-- Navbar -->
      @include('panel.Navbar')
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    @auth()
        @include('panel.sidbar_'.\Illuminate\Support\Facades\Auth::user()->type)
    @else
        @include('panel.sidbar_teacher')
    @endauth
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                @yield('content')

                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->

        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>CopyLeft &copy; 2018 <a href="#">سامانه یار مهربان</a>.</strong>
    </footer>

    <!-- Control Sidebar -->

    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
@include('panel.frontend.js')
</body>
</html>

resources/views/panel/sidbar_student.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4" style="">
    <!-- Sidebar -->
    <div class="sidebar" style="">
        <div>
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image mx-auto d-block">
                    <img src="http://yaremehraban.org/web_src/dist/img/logo-yaremehraban.png" alt="User Image">
                </div>
            </div>
            <div class="user-panel pb-3 mb-3 d-flex text-center">
            <div class="w-100 info">
              <a href="#" class="d-block">شبکه آنلاین یار مهربان<br>(مدرسه امام علی)</a>
            </div>
          </div>
            </div>
            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <li class="nav-item has-treeview menu-close">
                        <a href="" class="nav-link active">
                            <i class="nav-icon fa fa-dashboard"></i>
                            <p>
                                منو ها
                                <i class="right fa fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{url('dashboard')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>داشبورد</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('student.calender.index')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>تقویم</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('student.online.index')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>کلاس آنلاین</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('student.task.index')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>تکلیف</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <i class="fa fa-circle-o nav-icon"></i> <span>آزمون</span>
                                </a>
                            </li>
                                <li class="nav-item">
                                    <li class="active"><a class="nav-link" href="{{route('student.homework.index_test')}}"><i class="fa fa-circle-o"></i>آزمون تستی دانش آموز</a></li>
                                    <li><a class="nav-link" href="{{route('student.homework.index_descriptive')}}"><i class="fa fa-circle-o"></i>آزمون تشریحی</a></li>
                                </li>
                            <li class="nav-item">
                                <a href="{{route('student.report_card.index')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>کارنامه</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{url('bulletin')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>تابلو اعلانات</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('student.disciplinary.index')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>مورد انضباطی</p>
                                </a>
                            </li>
                            <li class="nav-item has-treeview menu-close menu-close">
                    <a href="#" class="nav-link hadipadding">
                        <i class="fa fa-plus-square-o"></i>
                        <p>
                            گزارش و نمودار <i class="right fa fa-angle-left"></i> </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/defineTeacher" class="nav-link">
                                <i class=""></i>
                                <p>ارزیابی عملکرد مطالعاتی</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/createStudent" class="nav-link">
                                <i class=""></i>
                                <p>نسبت مطالعه به نمره</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/defineClass" class="nav-link">
                                <i class=""></i>
                                <p>پیشرفت تحصیلی</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/defineEmployee" class="nav-link">
                                <i class=""></i>
                                <p>ثبت مطالعه درسی</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/defineEmployee" class="nav-link">
                                <i class=""></i>
                                <p>نمودار مقایسه کلاسی</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/defineEmployee" class="nav-link">
                                <i class=""></i>
                                <p>ارزیابی آموزشی</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview menu-close menu-close">
                    <a href="#" class="nav-link hadipadding">
                        <i class="fa fa-plus-square-o"></i>
                        <p>
                           پشتیبانی <i class="right fa fa-angle-left"></i> </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/defineTeacher" class="nav-link">
                                <i class=""></i>
                                <p>ارسال تیکت</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/createStudent" class="nav-link">
                                <i class=""></i>
                                <p>فهرست تیکت ها</p>
                            </a>
                        </li>
                    </ul>
                </li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/panel/sidbar_teacher.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">

    <!-- Sidebar -->
    <div class="sidebar">
        <div>
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="row">
                    <div class="col-12 text-center"><img src=""/></div>
                    <div class="col-12 text-center" style="font-size: 14px; color: #c2c7d0;">شبکه آنلاین یار مهربان
                    </div>
                    <div class="col-12 pb-3 text-center" style="font-size: 14px; color: #c2c7d0;">(مدرسه کمالی)</div>
                    <div class="col-12 text-center image">
                        <img src="{{asset('img/logo-yaremehraban.png')}}" class="img-circle elevation-2"
                             alt="User Image">
                    </div>
                    <div class="col-12 text-center info">
                        <a href="#" class="d-block"> <span style="font-size: 12px"></span></a>
                    </div>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <li class="nav-item has-treeview menu-close">
                        <a href="" class="nav-link active">
                            <i class="nav-icon fa fa-dashboard"></i>
                            <p>
                                منو ها
                                <i class="right fa fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{url('dashboard')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>داشبورد</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('teacher.calender.index')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>تقویم</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('teacher.online.index')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>کلاس آنلاین</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('teacher.task.index')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>تکلیف</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('teacher.homework.index')}}">
                                    <i class="fa fa-circle-o nav-icon"></i> <span>آزمون</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('teacher.report_card.index')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>کارنامه</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{url('bulletin')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>تابلو اعلانات</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('teacher.disciplinary.index')}}" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>مورد انضباطی</p>
                                </a>
                            </li>
                            <li class="nav-item has-treeview menu-close menu-close">
                    <a href="#" class="nav-link hadipadding">
                        <i class="fa fa-plus-square-o"></i>
                        <p>
                            گزارش و نمودار <i class="right fa fa-angle-left"></i> </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/defineTeacher" class="nav-link">
                                <i class=""></i>
                                <p>ارزیابی عملکرد مطالعاتی</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/createStudent" class="nav-link">
                                <i class=""></i>
                                <p>نسبت مطالعه به نمره</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/defineClass" class="nav-link">
                                <i class=""></i>
                                <p>پیشرفت تحصیلی</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/defineEmployee" class="nav-link">
                                <i class=""></i>
                                <p>ثبت مطالعه درسی</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/defineEmployee" class="nav-link">
                                <i class=""></i>
                                <p>نمودار مقایسه کلاسی</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/defineEmployee" class="nav-link">
                                <i class=""></i>
                                <p>ارزیابی آموزشی</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview menu-close menu-close">
                    <a href="#" class="nav-link hadipadding">
                        <i class="fa fa-plus-square-o"></i>
                        <p>
                           پشتیبانی <i class="right fa fa-angle-left"></i> </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/defineTeacher" class="nav-link">
                                <i class=""></i>
                                <p>ارسال تیکت</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item" style="background-color: #0358a0;">
                            <a href="http://yaremehraban.org/panel/main/createStudent" class="nav-link">
                                <i class=""></i>
                                <p>فهرست تیکت ها</p>
                            </a>
                        </li>
                    </ul>
                </li>
                        </ul>
                    </li>
                            </ul>
                        </ul>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
    </div>
    <!-- /.sidebar -->
</aside>